name: Magisk Modules Sync
on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync Magisk Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          git clone -b main https://github.com/ya0211/magisk-modules-repo-util.git util
          python -m pip install --upgrade pip
          pip install python-dateutil requests

      - name: Create config.json
        run: |
          python util/cli.py github --user-name Magisk-Modules-Alt-Repo --api-token=${{ secrets.GITHUB_TOKEN }}
          python util/cli.py config --write repo_name="Magisk-Modules-Alt-Repo" repo_url="https://rushizgithub.github.io/mrepo/" max_num=3 show_log=true log_dir="log"

#       - name: Create track.json
#         run: |
#           python util/cli.py module --add id="zygisk_lsposed" update_to="https://lsposed.github.io/LSPosed/release/zygisk.json" license="GPL-3.0"

      - name: Start Sync
        run: |
          python util/cli.py sync
